application:
  name: 'Senacor Juice Shop'
  logo: JuiceShopCTF_Logo.png
  favicon: favicon_ctf.ico
  showChallengeHints: true
  showVersionNumber: false
  showHackingInstructor: false
  gitHubRibbon: false
ctf:
  showFlagsInNotifications: true